%YAML:1.0
# Dummies for directional light sources
light_positions:
 - {x: 0.0, y: 0.0, z: 0.0}
 - {x: 0.0, y: 0.0, z: 0.0}
 - {x: 0.0, y: 0.0, z: 0.0}

light_directions:
 - {x: 0.0, y: -1.0, z: 0.0}
 - {x: -1.0, y: -1.0, z: 0.0}
 - {x: 0.0, y: -1.0, z: -1.0}

light_color: {r: 1.0, g: 1.0, b: 1.0}
light_power: 0.2

material_ambient_coeff: {r: 0.3, g: 0.3, b: 0.3}
material_specular_coeff: {r: 0.0, g: 0.0, b: 0.0}
material_diffuse_color: {r: 0.8, g: 0.8, b: 0.8}